// Dockerfile para NestJS (api)
FROM node:22-alpine AS base
WORKDIR /app
COPY . .
RUN corepack enable && corepack prepare pnpm@latest --activate
RUN pnpm install --frozen-lockfile
RUN pnpm build
EXPOSE 3001
CMD ["pnpm", "start:prod"]
